services:
  reverse-regex:
    image: ghcr.io/trust-psp/base-php-local:8.5
    tty: true
    user: ${UID:-1000}
    restart: "no"
    volumes:
      - .:/app:rw
    working_dir: /app
    command: >
      sh -c "
        php /build/scripts/LoadGithubAuth.php &&
        php /build/scripts/LoadGitHooks.php &&
        php /usr/bin/composer install &&
        tail -f /dev/null
      "
    container_name: ${CONTAINER_NAME:-reverse-regex}
